//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAQLKSEntities : DbContext
    {
        public DAQLKSEntities()
            : base("name=DAQLKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ChiTieuPhieuThue> tbl_ChiTieuPhieuThue { get; set; }
        public virtual DbSet<tbl_ChucVu> tbl_ChucVu { get; set; }
        public virtual DbSet<tbl_DichVu> tbl_DichVu { get; set; }
        public virtual DbSet<tbl_DichVuDaDat> tbl_DichVuDaDat { get; set; }
        public virtual DbSet<tbl_HoaDon> tbl_HoaDon { get; set; }
        public virtual DbSet<tbl_KhachHang> tbl_KhachHang { get; set; }
        public virtual DbSet<tbl_LoaiDichVu> tbl_LoaiDichVu { get; set; }
        public virtual DbSet<tbl_LoaiKhach> tbl_LoaiKhach { get; set; }
        public virtual DbSet<tbl_LoaiPhong> tbl_LoaiPhong { get; set; }
        public virtual DbSet<tbl_NhanVien> tbl_NhanVien { get; set; }
        public virtual DbSet<tbl_PhieuThuePhong> tbl_PhieuThuePhong { get; set; }
        public virtual DbSet<tbl_Phong> tbl_Phong { get; set; }
        public virtual DbSet<tbl_TrangThaiDichVu> tbl_TrangThaiDichVu { get; set; }
        public virtual DbSet<tbl_TrangThaiPhong> tbl_TrangThaiPhong { get; set; }
        public virtual DbSet<tbl_ChiTietPhong> tbl_ChiTietPhong { get; set; }
    }
}
